---
abstract: 'DICOM UID generator.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dicom-UID-Generator
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.07
  DateTime::HiRes: 0
  English: 0
  Readonly: 0
  perl: 5.8.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dicom-UID-Generator
  homepage: https://github.com/michal-josef-spacek/Dicom-UID-Generator
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Dicom-UID-Generator
version: '0.02'
